name: Build

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md

env:
  PROJECT_NAME: diator

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 9
          submodules: false

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          make test

      - name: Run linters
        run: |
          make check-linting

    services:
      redis:
        image: redis:alpine
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        ports:
          - 6379:6379
